name: build-test-pull-request
on: [pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: npm run test

      - name: Coverage
        run: npm run test:cov